---
title: "Beating the odds"
author: "MaryJo Webster"
date:  "Last updated: `r Sys.Date()`"
output:
  html_document: 
    toc: true
    to_depth: 1
    toc_float: true
    theme: flatly
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, cache=FALSE, fig.height = 6, fig.width = 8)


library(readr) #importing csv files
library(dplyr) #general analysis 
library(ggplot2) #making charts
library(lubridate) #date functions
library(reshape2) #use this for melt function to create one record for each team
library(tidyr)
library(janitor) #use this for doing crosstabs
library(scales) #needed for stacked bar chart axis labels
library(knitr) #needed for making tables in markdown page
library(aws.s3)
library(htmltools)#this is needed for Rstudio to display kable and other html code
library(rmarkdown)
library(readxl)
library(DT) #needed for making  searchable sortable data tble
library(kableExtra)
library(ggthemes)
```


```{r}
#import files that were created in the 'process_test_score_data' script

beatingodds_math <- read_csv('./data/beatingodds_math.csv')
beatingodds_read <-  read_csv('./data/beatingodds_read.csv')
math_over_time <-  read_csv('./data/math_over_time.csv')
read_over_time <-  read_csv('./data/read_over_time.csv')
```




#Math
Metro, high-poverty schools beating odds in math this year<br>
How they did in prior years (starting with 12-13)<br>
Some don't have data for all years

```{r }

math_over_time %>% tabyl(school_name, categoryname) %>% 
  adorn_totals("col") %>%
  #adorn_percentages("row") %>%
  #adorn_pct_formatting(rounding = "half up", digits = 0) %>%
   #adorn_ns() %>% 
   adorn_title("top")%>%
  knitr::kable("html") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F, position="left")
```


#Reading
Metro, high-poverty schools beating odds in reading this year<br>
How they did in prior years (starting with 12-13)<br>
Some don't have data for all years

```{r}


read_over_time %>% tabyl(school_name, categoryname) %>% 
  adorn_totals("col") %>%
  #adorn_percentages("row") %>%
  #adorn_pct_formatting(rounding = "half up", digits = 0) %>%
   #adorn_ns() %>% 
   adorn_title("top")%>%
  knitr::kable("html") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F, position="left")
```




```{r movetoS3, echo=FALSE, eval=FALSE, results="hide"}




Sys.setenv("AWS_ACCESS_KEY_ID" =  rstudioapi::askForPassword("AWS_ACCESS_KEY_ID"),

           "AWS_SECRET_ACCESS_KEY" = rstudioapi::askForPassword("AWS_SECRET_ACCESS_KEY"))
		   
		   get_bucket("strib-data-internal")


put_object(file = "beatingodds.html", object = "projects/schools/beatingodds.html", bucket = "strib-data-internal")

put_object(file = "beatingodds.html", object = "projects/schools/beatingodds.html", bucket = "strib-data-internal", acl=c("public-read"))



```
